config/routes.rb
Rails.application.routes.draw do
  resources :boards do
    resources :pedals do
      resources :knobs
    end
  end


  root "sessions#new"
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/userhome' => "users#show"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy"
end

app/models/board.rb
class Board < ActiveRecord::Base
    belongs_to :user
    has_many :pedals
    validates :title, presence: true
    validates_format_of :audio, with: /https:\/\/soundcloud\.com\//, :allow_blank => true
    validates :instrument, presence: true



    def setup_id(current_user)
        self.user_id = current_user.id
    end

    def getSoundCloud(url)
            track = $client.get('/resolve', :url => url)
            track_id = track.id
    end

end

app/models/knob.rb
class Knob < ActiveRecord::Base
    belongs_to :pedal, dependent: :destroy
end

app/models/pedal.rb
class Pedal < ActiveRecord::Base
    belongs_to :board, dependent: :destroy
    has_many :knobs

    validates :name, presence: true
    validates :effect, presence: true
    validates :brand, presence: true

    accepts_nested_attributes_for :knobs

end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    has_many :boards
    validates :name, presence: true, uniqueness: {case_sensitive: false}
    validates :email, presence: true, uniqueness: {case_sensitive: false}
    validates_presence_of :password, presence: true, confirmation: true, :on => :create


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :require_user

    def current_user
      if session[:user_id]
         @current_user||= User.find(session[:user_id])
           return @current_user
       else
           return nil
       end
    end


    def require_user
     redirect_to '/login' unless current_user
    end

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    before_action :require_user

    def index
        @user = current_user.id
        if params[:search] && params[:search] != ""
            user = User.where(name: params[:search])
            @boards = user.first.boards
        else
            @boards = Board.where.not(user_id: @user)
        end
    end

    def new
        @board = Board.new
    end

    def show
        @board = Board.find(params[:id])
    end

    def create
        @board = Board.new(board_params)
        @board.setup_id(current_user)
            if @board.save
                redirect_to "/userhome"
            else
                flash[:error] = @board.errors.full_messages.to_sentence
                render "new"
            end
    end

    def edit
        @board = Board.find(params[:id])
    end

    def update
        @board = Board.find(params[:id])
        if @board.update_attributes(board_params)
            redirect_to "/userhome"
        end
    end

    def destroy
        @board = Board.find(params[:id])
        @board.destroy
        redirect_to "/userhome"
    end

    private

    def board_params
        params.require(:board).permit(:title, :audio, :instrument, pedals_attributes:[:id, :board_id, :name, :brand, :effect, knobs_attributes:[:name, :value]])
    end
end

app/controllers/knobs_controller.rb
class KnobsController < ApplicationController
    before_action :require_user

    def new
        @knob = Knob.new
    end

    def create

        @knob = pedal.knob.build(knob_params)
        if @knob.save
            redirect_to '/userhome'
        else
            render "new"
        end
    end

    private

    def knob_params
        params.require(:knob).permit(:name, :value)
    end
end

app/controllers/pedals_controller.rb
class PedalsController < ApplicationController
    before_action :require_user

    def new
        @board = Board.find(params[:board_id])
        @pedal = @board.pedals.new
        @knob = @pedal.knobs.new
    end

    def create
        @board = Board.find(params[:board_id])
        @pedal = @board.pedals.build(pedal_params)
        if @pedal.save
            redirect_to "/userhome"
        else
            render "new"
        end
    end

    def edit
        @board = Board.find(params[:board_id])
        @pedal = @board.pedals.find(params[:id])
    end

    def update
        @board = Board.find(params[:board_id])
        @pedal = Pedal.find(params[:id])
        if @pedal.update_attributes(pedal_params)
            redirect_to "/userhome"
        end
    end

    private

    def pedal_params
        params.require(:pedal).permit(:name, :brand, :effect, knobs_attributes: [:id, :name, :value])
    end

    # def knob_params
    #     params.require(:knob).permit(:name, :value)
    # end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
     # Makes new user
    def new
        @user = User.new
    end

    # Creates new session
    def create
        user = User.find_by_name(params[:name])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to "/userhome"
        else
            flash[:error] = "Login information incorrect"
            redirect_to login_path
        end
    end

    #Ends session
    def destroy
        session[:user_id] = nil
        redirect_to ('/login')
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to '/userhome'
        else
            flash[:error] = @user.errors.full_messages.to_sentence
            redirect_to('/signup')
        end
    end

    def show
        if current_user
            @user = current_user
        else
            redirect_to "/login"
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/knobs_helper.rb
module KnobsHelper
end

app/helpers/pedals_helper.rb
module PedalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/index.html.erb
<%= form_tag boards_path, :method => 'get' do %>
  <div class="text-center">
    <%= text_field_tag :search, params[:search] %>
    </br>
    <%= submit_tag "Search", :name => nil, class: "btn btn-default" %>
  </div>
<% end %>

<% @boards.each do |b| %>
    <div class="board text-center">
        <h1><%= b.title %> - <%= b.instrument %></h1>
        <h2>By: <%= b.user.name %></h2>
        <% unless b.audio == nil || b.audio == "" %>
        <iframe width="50%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/<%= b.getSoundCloud(b.audio) %>&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe>
        <% end %>
        <br/>


    <div class="grid">
        <% b.pedals.each do |p| %>
            <div class="grid-item pedal">
                <h4 class="pedal_details">
                    <%= p.name %>
                    <br/>
                    <%= p.brand %>
                    <br/>
                    <%= p.effect %>
                </h4>
                <br/>
                <ul class="list-group">
                    <% p.knobs.each do |k| %>
                    <li class="list-group-item text-left">
                    <%= image_tag('knob.png', class: 'knob')%>
                    <%= k.name %>
                    :
                    <%= k.value %>
                    </li>
                    <% end %>
                </ul>
             </div>
         <% end %>
    </div>


    </div>
<% end %>

app/views/boards/new.html.erb
<p><%= flash[:error] %></p>
<div class="form-group board row col-sm-6">
        <%= form_for @board do |f| %>
            <h3><%= f.label :title %></h3>
            <h4>Give your new board a name</h4>
            <%= f.text_field :title, class: "form-control" %>
            <br/>
            <h3><%= f.label :audio %></h3>
            <h4>If you have a SoundCloud sample of this board, put the URL here</h4>
            <%= f.text_field :audio, class: "form-control" %>
            <br/>
            <h3><%= f.label :instrument %></h3>
            <h4>What are you playing through this board? Guitar? Bass? Keyboard?</h4>
            <%= f.text_field :instrument, class: "form-control" %>
            <div class="submit-btn">
            <%= f.submit "Create this Board", class: "btn btn-default" %>
            </div>
        <% end %>
</div>

app/views/boards/show.html.erb
<h1><%= @board.title %></h1>
<br/>
<div class="text-center">
    <%= link_to "Add a Pedal", new_board_pedal_path(@board), class: 'btn btn-default' %>
    <%= link_to "Delete this Board", @board, method: :delete, class: 'btn btn-default' %>
    </div>
    <div class="container board">
    <div class="grid space">
    <% @board.pedals.each do |pedal| %>
    <div class="grid-item pedal">
    <%= link_to edit_board_pedal_path(@board, pedal) do %>
        <h4 class="pedal_details">
            <%= pedal.name %>
            <br/>
            <%= pedal.brand %>
            <br/>
            <%= pedal.effect %>
            </h4>
        <ul class="list-group">
            <% pedal.knobs.each do |k| %>
            <li class="list-group-item">
            <%= image_tag('knob.png', class: 'knob')%>
            <%= k.name %>
            :
            <%= k.value %>
            </li>
            <% end %>
            </ul>
    </div>
    <% end %>
    <% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TonalRecall</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= google_webfonts_init({
        google: ['Rhodium Libre', 'Work Sans']
  }) %>
</head>
<body>
<!-- Nav bar -->
    <nav class="navbar navbar-default well customnav" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="glyphicon glyphicon-menu-hamburger"></i>
                </button>
        </div>
        <div class="collapse navbar-collapse navbar-main-collapse">
            <ul class="nav navbar-nav navbar-left">
              <% if current_user %>
              <li><%= link_to "My Pedal Boards", '/userhome'%></li>
              <li><%= link_to "Create a Board", new_board_path, class: 'navbar-link'%></li>
              <li><%= link_to "Other Boards", boards_path, class: 'navbar-link' %></li>
              <% end %>
            </ul>


            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
                <li><p class="navbar-text">Hello,<strong> <%= current_user.name %></strong></p></li>

                <li><%= link_to "Logout", '/logout'%></li>
              <% else %>
                <li><%= link_to "Login", '/login'%></li>
                <li><%= link_to "Sign Up", '/signup'%></li>
              <% end %>
            </ul>

        </div>
      </div>
    </nav>

<div class="container">
<%= yield %>
</div>


</body>
</html>

app/views/pedals/_form.html.erb
<%= form_for [@board, @pedal] do |f| %>

   <%=  f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :brand %>
    <%= f.text_field :brand %>
    <%= f.label :effect %>
    <%= f.text_field :effect %>
  <h2>Knobs:</h2>
  <% f.fields_for :knobs do |knob| %>
    <%= render "knob_fields", :f => knob %>
  <% end %>
  <br/>
  <p><%= link_to_add_association "Add Knob", f, :knobs, class: "btn btn-default tag-tooltip",
                    :data => {:toggle=>"tooltip"},
                    'data-original-title' => "Please use o'clock notation for dials - on/off for toggles",
                    'data-placement' => 'right'%></p>
  <p><%= f.submit "Submit", class: "btn btn-default" %></p>
<% end %>

app/views/pedals/_knob_fields.html.erb
<div class="nested-fields">
<p class="fields">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :value %>
    <%= f.text_field :value %>
    <%= link_to_remove_association "Remove", f %>
</p>
</div>

app/views/pedals/edit.html.erb
<div class="form-group board">
<%= form_for [@board, @pedal] do |f| %>
    <h1>Pedal:</h1>
   <%=  f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :brand %>
    <%= f.text_field :brand %>
    <%= f.label :effect %>
    <%= f.text_field :effect %>
    <br/>
    <h1>Knobs:</h1>
    <%= f.fields_for :knobs do |k| %>
        <%= k.label :name %>
        <%= k.text_field :name %>
        <%= k.label :value %>
        <%= k.text_field :value %>
        <br/>
    <% end %>
    <%= f.submit "Submit", class: "btn btn-default" %>
<% end %>
</div>

app/views/pedals/new.html.erb
<h1>New Pedal:</h1>

<div class="form-group board">
        <%= render 'form' %>
</div>

app/views/users/new.html.erb
<h1>Sign up for an account</h1>

<p><%= flash[:error] %></p>
<div class="form-group board row col-sm-6">
    <%= form_for (@user) do |f| %>

        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
        <br/>


        <%= f.label :email%>
        <%= f.email_field :email, class: "form-control" %>
        <br/>

        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
        <br/>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
        <%= f.submit "Submit", class: "btn submit-btn btn-default" %></li>
    <% end %>
</div>
<div class="get-ready-to-rock row col-sm-6">
    <h1 class="grtr-line">GET</h1>
    <h1 class="grtr-line">READY</h1>
    <h1 class="grtr-line">TO</h1>
    <h1 class="grtr-line">ROCK</h1>
</div>

app/views/users/show.html.erb
<h1 class="text-center"><%= @user.name %>'s Boards</h1>

<% if @user.boards.length < 1 %>
    <h2 class="text-center">You haven't created any pedal boards yet!</h2>
    <h2 class="text-center">Get started by clicking 'Create a Board' in the nav above.</h2>
<% end %>

<% @user.boards.each do |b| %>
    <div class=" container board text-center">
        <h1><%= b.title %> - <%= b.instrument %></h1>
        <%= link_to "Edit", board_path(b), class: "btn btn-default tag-tooltip",
                    :data => {:toggle=>"tooltip"},
                    'data-original-title' => "Add Pedals",
                    'data-placement' => 'right'%>
        <% unless b.audio == nil || b.audio == "" %>
        <div class="soundcloud"><iframe width="50%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/<%= b.getSoundCloud(b.audio) %>&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe></div>
        <% end %>
        <br/>


    <div class="grid">
        <% b.pedals.each do |p| %>
        <div class="grid-item pedal">
        <h4 class="pedal_details">
        <%= p.name %>
        <br/>
        <%= p.brand %>
        <br/>
        <%= p.effect %>
        </h4>
        <br/>
        <ul class="list-group">
        <% p.knobs.each do |k| %>
        <li class="list-group-item text-left">
        <%= image_tag('knob.png', class: 'knob')%>
        <%= k.name %>
        :
        <%= k.value %>
        </li>
        <% end %>
        </ul>
         </div>
         <% end %>
    </div>


    </div>
<% end %>